export const SECTOR_COLORS = {
  'Technology': '#3b82f6',
  'Healthcare': '#10b981',
  'Financials': '#f59e0b',
  'Consumer Disc.': '#8b5cf6',
  'Industrials': '#06b6d4',
  'Comm. Services': '#ec4899',
  'Energy': '#ef4444',
  'Real Estate': '#14b8a6',
  'Consumer Staples': '#a78bfa',
  'Materials': '#fb923c',
  'Utilities': '#4ade80',
  'Fixed Income': '#38bdf8',
  'Other': '#94a3b8',
}

export const ETF_UNIVERSE = [
  // ── US Equity Broad ───────────────────────────────────────────────────────
  {
    symbol: 'SPY', name: 'SPDR S&P 500 ETF', issuer: 'State Street',
    category: 'US Equity Broad', benchmark: 'S&P 500',
    aum: '504B', er: 0.0945, holdings: 503, domicile: 'US',
    replication: 'Physical', esgScore: null,
    topHoldings: [
      { symbol: 'AAPL', name: 'Apple', weight: 7.21, sector: 'Technology' },
      { symbol: 'MSFT', name: 'Microsoft', weight: 6.84, sector: 'Technology' },
      { symbol: 'NVDA', name: 'NVIDIA', weight: 6.12, sector: 'Technology' },
      { symbol: 'AMZN', name: 'Amazon', weight: 3.87, sector: 'Consumer Disc.' },
      { symbol: 'META', name: 'Meta', weight: 2.63, sector: 'Comm. Services' },
      { symbol: 'GOOGL', name: 'Alphabet A', weight: 2.08, sector: 'Comm. Services' },
      { symbol: 'GOOG', name: 'Alphabet C', weight: 1.78, sector: 'Comm. Services' },
      { symbol: 'BRK.B', name: 'Berkshire B', weight: 1.71, sector: 'Financials' },
      { symbol: 'LLY', name: 'Eli Lilly', weight: 1.64, sector: 'Healthcare' },
      { symbol: 'JPM', name: 'JPMorgan', weight: 1.61, sector: 'Financials' },
    ],
    sectors: [
      { name: 'Technology', weight: 29.5 }, { name: 'Financials', weight: 13.2 },
      { name: 'Healthcare', weight: 12.8 }, { name: 'Consumer Disc.', weight: 10.7 },
      { name: 'Industrials', weight: 8.5 }, { name: 'Comm. Services', weight: 8.9 },
      { name: 'Energy', weight: 3.8 }, { name: 'Consumer Staples', weight: 5.1 },
      { name: 'Real Estate', weight: 2.4 }, { name: 'Materials', weight: 2.5 },
      { name: 'Utilities', weight: 2.6 },
    ],
    stressTests: { gfc2008: -55, covid2020: -34, rateShock2022: -25 },
    flags: { currencyHedged: false, swapBased: false, concentrationRisk: false, esgScreened: false },
    distFreq: 'Quarterly',
  },
  {
    symbol: 'IVV', name: 'iShares Core S&P 500 ETF', issuer: 'iShares (BlackRock)',
    category: 'US Equity Broad', benchmark: 'S&P 500',
    aum: '478B', er: 0.03, holdings: 503, domicile: 'US',
    replication: 'Physical', esgScore: null,
    topHoldings: [
      { symbol: 'AAPL', name: 'Apple', weight: 7.21, sector: 'Technology' },
      { symbol: 'MSFT', name: 'Microsoft', weight: 6.84, sector: 'Technology' },
      { symbol: 'NVDA', name: 'NVIDIA', weight: 6.12, sector: 'Technology' },
      { symbol: 'AMZN', name: 'Amazon', weight: 3.87, sector: 'Consumer Disc.' },
      { symbol: 'META', name: 'Meta', weight: 2.63, sector: 'Comm. Services' },
      { symbol: 'GOOGL', name: 'Alphabet A', weight: 2.08, sector: 'Comm. Services' },
      { symbol: 'GOOG', name: 'Alphabet C', weight: 1.78, sector: 'Comm. Services' },
      { symbol: 'BRK.B', name: 'Berkshire B', weight: 1.71, sector: 'Financials' },
      { symbol: 'LLY', name: 'Eli Lilly', weight: 1.64, sector: 'Healthcare' },
      { symbol: 'JPM', name: 'JPMorgan', weight: 1.61, sector: 'Financials' },
    ],
    sectors: [
      { name: 'Technology', weight: 29.5 }, { name: 'Financials', weight: 13.2 },
      { name: 'Healthcare', weight: 12.8 }, { name: 'Consumer Disc.', weight: 10.7 },
      { name: 'Industrials', weight: 8.5 }, { name: 'Comm. Services', weight: 8.9 },
      { name: 'Energy', weight: 3.8 }, { name: 'Consumer Staples', weight: 5.1 },
      { name: 'Real Estate', weight: 2.4 }, { name: 'Materials', weight: 2.5 },
      { name: 'Utilities', weight: 2.6 },
    ],
    stressTests: { gfc2008: -55, covid2020: -34, rateShock2022: -25 },
    flags: { currencyHedged: false, swapBased: false, concentrationRisk: false, esgScreened: false },
    distFreq: 'Quarterly',
  },
  {
    symbol: 'VOO', name: 'Vanguard S&P 500 ETF', issuer: 'Vanguard',
    category: 'US Equity Broad', benchmark: 'S&P 500',
    aum: '466B', er: 0.03, holdings: 503, domicile: 'US',
    replication: 'Physical', esgScore: null,
    topHoldings: [
      { symbol: 'AAPL', name: 'Apple', weight: 7.21, sector: 'Technology' },
      { symbol: 'MSFT', name: 'Microsoft', weight: 6.84, sector: 'Technology' },
      { symbol: 'NVDA', name: 'NVIDIA', weight: 6.12, sector: 'Technology' },
      { symbol: 'AMZN', name: 'Amazon', weight: 3.87, sector: 'Consumer Disc.' },
      { symbol: 'META', name: 'Meta', weight: 2.63, sector: 'Comm. Services' },
      { symbol: 'GOOGL', name: 'Alphabet A', weight: 2.08, sector: 'Comm. Services' },
      { symbol: 'GOOG', name: 'Alphabet C', weight: 1.78, sector: 'Comm. Services' },
      { symbol: 'BRK.B', name: 'Berkshire B', weight: 1.71, sector: 'Financials' },
      { symbol: 'LLY', name: 'Eli Lilly', weight: 1.64, sector: 'Healthcare' },
      { symbol: 'JPM', name: 'JPMorgan', weight: 1.61, sector: 'Financials' },
    ],
    sectors: [
      { name: 'Technology', weight: 29.5 }, { name: 'Financials', weight: 13.2 },
      { name: 'Healthcare', weight: 12.8 }, { name: 'Consumer Disc.', weight: 10.7 },
      { name: 'Industrials', weight: 8.5 }, { name: 'Comm. Services', weight: 8.9 },
      { name: 'Energy', weight: 3.8 }, { name: 'Consumer Staples', weight: 5.1 },
      { name: 'Real Estate', weight: 2.4 }, { name: 'Materials', weight: 2.5 },
      { name: 'Utilities', weight: 2.6 },
    ],
    stressTests: { gfc2008: -55, covid2020: -34, rateShock2022: -25 },
    flags: { currencyHedged: false, swapBased: false, concentrationRisk: false, esgScreened: false },
    distFreq: 'Quarterly',
  },
  {
    symbol: 'VTI', name: 'Vanguard Total Stock Market ETF', issuer: 'Vanguard',
    category: 'US Equity Broad', benchmark: 'CRSP US Total Market',
    aum: '433B', er: 0.03, holdings: 3762, domicile: 'US',
    replication: 'Sampling', esgScore: null,
    topHoldings: [
      { symbol: 'AAPL', name: 'Apple', weight: 5.84, sector: 'Technology' },
      { symbol: 'MSFT', name: 'Microsoft', weight: 5.51, sector: 'Technology' },
      { symbol: 'NVDA', name: 'NVIDIA', weight: 4.93, sector: 'Technology' },
      { symbol: 'AMZN', name: 'Amazon', weight: 3.12, sector: 'Consumer Disc.' },
      { symbol: 'META', name: 'Meta', weight: 2.14, sector: 'Comm. Services' },
      { symbol: 'GOOGL', name: 'Alphabet A', weight: 1.68, sector: 'Comm. Services' },
      { symbol: 'TSLA', name: 'Tesla', weight: 1.52, sector: 'Consumer Disc.' },
      { symbol: 'BRK.B', name: 'Berkshire B', weight: 1.38, sector: 'Financials' },
      { symbol: 'LLY', name: 'Eli Lilly', weight: 1.32, sector: 'Healthcare' },
      { symbol: 'JPM', name: 'JPMorgan', weight: 1.29, sector: 'Financials' },
    ],
    sectors: [
      { name: 'Technology', weight: 28.4 }, { name: 'Financials', weight: 13.8 },
      { name: 'Healthcare', weight: 13.1 }, { name: 'Consumer Disc.', weight: 10.9 },
      { name: 'Industrials', weight: 9.2 }, { name: 'Comm. Services', weight: 8.4 },
      { name: 'Energy', weight: 3.6 }, { name: 'Consumer Staples', weight: 4.0 },
      { name: 'Real Estate', weight: 3.1 }, { name: 'Materials', weight: 2.8 },
      { name: 'Utilities', weight: 2.7 },
    ],
    stressTests: { gfc2008: -56, covid2020: -35, rateShock2022: -24 },
    flags: { currencyHedged: false, swapBased: false, concentrationRisk: false, esgScreened: false },
    distFreq: 'Quarterly',
  },
  {
    symbol: 'IWM', name: 'iShares Russell 2000 ETF', issuer: 'iShares (BlackRock)',
    category: 'US Equity Broad', benchmark: 'Russell 2000',
    aum: '68B', er: 0.19, holdings: 2000, domicile: 'US',
    replication: 'Physical', esgScore: null,
    topHoldings: [
      { symbol: 'SMCI', name: 'Super Micro', weight: 0.52, sector: 'Technology' },
      { symbol: 'ONTO', name: 'Onto Innovation', weight: 0.41, sector: 'Technology' },
      { symbol: 'CAVA', name: 'CAVA Group', weight: 0.38, sector: 'Consumer Disc.' },
      { symbol: 'INSP', name: 'Inspire Medical', weight: 0.36, sector: 'Healthcare' },
      { symbol: 'FTDR', name: 'Frontdoor', weight: 0.35, sector: 'Consumer Disc.' },
      { symbol: 'BOOT', name: 'Boot Barn', weight: 0.34, sector: 'Consumer Disc.' },
      { symbol: 'RXST', name: 'RxSight', weight: 0.33, sector: 'Healthcare' },
      { symbol: 'CVCO', name: 'Cavco Industries', weight: 0.32, sector: 'Consumer Disc.' },
      { symbol: 'PIPR', name: 'Piper Sandler', weight: 0.31, sector: 'Financials' },
      { symbol: 'VRRM', name: 'Verra Mobility', weight: 0.30, sector: 'Industrials' },
    ],
    sectors: [
      { name: 'Financials', weight: 17.8 }, { name: 'Industrials', weight: 17.2 },
      { name: 'Healthcare', weight: 14.9 }, { name: 'Technology', weight: 12.4 },
      { name: 'Consumer Disc.', weight: 10.8 }, { name: 'Energy', weight: 7.2 },
      { name: 'Consumer Staples', weight: 3.4 }, { name: 'Real Estate', weight: 6.1 },
      { name: 'Materials', weight: 3.9 }, { name: 'Utilities', weight: 3.1 },
      { name: 'Comm. Services', weight: 3.2 },
    ],
    stressTests: { gfc2008: -60, covid2020: -41, rateShock2022: -21 },
    flags: { currencyHedged: false, swapBased: false, concentrationRisk: false, esgScreened: false },
    distFreq: 'Quarterly',
  },
  // ── US Equity Factor ──────────────────────────────────────────────────────
  {
    symbol: 'QQQ', name: 'Invesco QQQ Trust', issuer: 'Invesco',
    category: 'US Equity Factor', benchmark: 'Nasdaq-100',
    aum: '259B', er: 0.20, holdings: 101, domicile: 'US',
    replication: 'Physical', esgScore: null,
    topHoldings: [
      { symbol: 'MSFT', name: 'Microsoft', weight: 8.92, sector: 'Technology' },
      { symbol: 'AAPL', name: 'Apple', weight: 8.43, sector: 'Technology' },
      { symbol: 'NVDA', name: 'NVIDIA', weight: 8.21, sector: 'Technology' },
      { symbol: 'AMZN', name: 'Amazon', weight: 5.14, sector: 'Consumer Disc.' },
      { symbol: 'META', name: 'Meta', weight: 4.87, sector: 'Comm. Services' },
      { symbol: 'TSLA', name: 'Tesla', weight: 3.42, sector: 'Consumer Disc.' },
      { symbol: 'GOOGL', name: 'Alphabet A', weight: 2.91, sector: 'Comm. Services' },
      { symbol: 'GOOG', name: 'Alphabet C', weight: 2.64, sector: 'Comm. Services' },
      { symbol: 'AVGO', name: 'Broadcom', weight: 2.48, sector: 'Technology' },
      { symbol: 'COST', name: 'Costco', weight: 2.31, sector: 'Consumer Staples' },
    ],
    sectors: [
      { name: 'Technology', weight: 51.2 }, { name: 'Comm. Services', weight: 15.8 },
      { name: 'Consumer Disc.', weight: 13.4 }, { name: 'Healthcare', weight: 6.2 },
      { name: 'Industrials', weight: 4.8 }, { name: 'Consumer Staples', weight: 4.3 },
      { name: 'Financials', weight: 2.4 }, { name: 'Energy', weight: 0.8 },
      { name: 'Other', weight: 1.1 },
    ],
    stressTests: { gfc2008: -49, covid2020: -28, rateShock2022: -33 },
    flags: { currencyHedged: false, swapBased: false, concentrationRisk: true, esgScreened: false },
    distFreq: 'Quarterly',
  },
  {
    symbol: 'VIG', name: 'Vanguard Dividend Appreciation ETF', issuer: 'Vanguard',
    category: 'US Equity Factor', benchmark: 'S&P US Dividend Growers',
    aum: '87B', er: 0.06, holdings: 338, domicile: 'US',
    replication: 'Physical', esgScore: null,
    topHoldings: [
      { symbol: 'MSFT', name: 'Microsoft', weight: 5.12, sector: 'Technology' },
      { symbol: 'AAPL', name: 'Apple', weight: 4.87, sector: 'Technology' },
      { symbol: 'JPM', name: 'JPMorgan', weight: 3.94, sector: 'Financials' },
      { symbol: 'UNH', name: 'UnitedHealth', weight: 3.72, sector: 'Healthcare' },
      { symbol: 'V', name: 'Visa', weight: 3.61, sector: 'Financials' },
      { symbol: 'AVGO', name: 'Broadcom', weight: 3.42, sector: 'Technology' },
      { symbol: 'MA', name: 'Mastercard', weight: 3.18, sector: 'Financials' },
      { symbol: 'JNJ', name: 'Johnson & Johnson', weight: 2.94, sector: 'Healthcare' },
      { symbol: 'HD', name: 'Home Depot', weight: 2.87, sector: 'Consumer Disc.' },
      { symbol: 'COST', name: 'Costco', weight: 2.71, sector: 'Consumer Staples' },
    ],
    sectors: [
      { name: 'Financials', weight: 22.4 }, { name: 'Technology', weight: 21.8 },
      { name: 'Healthcare', weight: 14.2 }, { name: 'Industrials', weight: 12.8 },
      { name: 'Consumer Disc.', weight: 10.4 }, { name: 'Consumer Staples', weight: 9.1 },
      { name: 'Comm. Services', weight: 4.2 }, { name: 'Materials', weight: 2.8 },
      { name: 'Energy', weight: 1.8 }, { name: 'Utilities', weight: 0.5 },
    ],
    stressTests: { gfc2008: -45, covid2020: -28, rateShock2022: -18 },
    flags: { currencyHedged: false, swapBased: false, concentrationRisk: false, esgScreened: false },
    distFreq: 'Quarterly',
  },
  {
    symbol: 'SCHD', name: 'Schwab US Dividend Equity ETF', issuer: 'Schwab',
    category: 'US Equity Factor', benchmark: 'Dow Jones US Dividend 100',
    aum: '62B', er: 0.06, holdings: 100, domicile: 'US',
    replication: 'Physical', esgScore: null,
    topHoldings: [
      { symbol: 'ABBV', name: 'AbbVie', weight: 4.61, sector: 'Healthcare' },
      { symbol: 'HD', name: 'Home Depot', weight: 4.38, sector: 'Consumer Disc.' },
      { symbol: 'TXN', name: 'Texas Instruments', weight: 4.22, sector: 'Technology' },
      { symbol: 'CVX', name: 'Chevron', weight: 4.17, sector: 'Energy' },
      { symbol: 'PEP', name: 'PepsiCo', weight: 4.03, sector: 'Consumer Staples' },
      { symbol: 'MO', name: 'Altria', weight: 3.87, sector: 'Consumer Staples' },
      { symbol: 'KO', name: 'Coca-Cola', weight: 3.72, sector: 'Consumer Staples' },
      { symbol: 'PFE', name: 'Pfizer', weight: 3.61, sector: 'Healthcare' },
      { symbol: 'AVGO', name: 'Broadcom', weight: 3.54, sector: 'Technology' },
      { symbol: 'MRK', name: 'Merck', weight: 3.42, sector: 'Healthcare' },
    ],
    sectors: [
      { name: 'Financials', weight: 18.4 }, { name: 'Healthcare', weight: 15.8 },
      { name: 'Consumer Staples', weight: 14.2 }, { name: 'Industrials', weight: 13.1 },
      { name: 'Technology', weight: 11.8 }, { name: 'Energy', weight: 9.2 },
      { name: 'Consumer Disc.', weight: 8.4 }, { name: 'Materials', weight: 4.8 },
      { name: 'Comm. Services', weight: 3.2 }, { name: 'Utilities', weight: 1.1 },
    ],
    stressTests: { gfc2008: null, covid2020: -27, rateShock2022: -14 },
    flags: { currencyHedged: false, swapBased: false, concentrationRisk: false, esgScreened: false },
    distFreq: 'Quarterly',
  },
  // ── US Sector ─────────────────────────────────────────────────────────────
  {
    symbol: 'XLK', name: 'Technology Select Sector SPDR', issuer: 'State Street',
    category: 'US Sector', benchmark: 'Technology Select Sector Index',
    aum: '68B', er: 0.10, holdings: 67, domicile: 'US',
    replication: 'Physical', esgScore: null,
    topHoldings: [
      { symbol: 'NVDA', name: 'NVIDIA', weight: 21.4, sector: 'Technology' },
      { symbol: 'AAPL', name: 'Apple', weight: 19.8, sector: 'Technology' },
      { symbol: 'MSFT', name: 'Microsoft', weight: 19.3, sector: 'Technology' },
      { symbol: 'AVGO', name: 'Broadcom', weight: 5.12, sector: 'Technology' },
      { symbol: 'CRM', name: 'Salesforce', weight: 3.94, sector: 'Technology' },
      { symbol: 'ORCL', name: 'Oracle', weight: 3.78, sector: 'Technology' },
      { symbol: 'AMD', name: 'AMD', weight: 3.42, sector: 'Technology' },
      { symbol: 'ACN', name: 'Accenture', weight: 3.21, sector: 'Technology' },
      { symbol: 'CSCO', name: 'Cisco', weight: 2.87, sector: 'Technology' },
      { symbol: 'ADBE', name: 'Adobe', weight: 2.54, sector: 'Technology' },
    ],
    sectors: [{ name: 'Technology', weight: 98.4 }, { name: 'Other', weight: 1.6 }],
    stressTests: { gfc2008: -55, covid2020: -28, rateShock2022: -35 },
    flags: { currencyHedged: false, swapBased: false, concentrationRisk: true, esgScreened: false },
    distFreq: 'Quarterly',
  },
  {
    symbol: 'XLF', name: 'Financial Select Sector SPDR', issuer: 'State Street',
    category: 'US Sector', benchmark: 'Financial Select Sector Index',
    aum: '42B', er: 0.10, holdings: 72, domicile: 'US',
    replication: 'Physical', esgScore: null,
    topHoldings: [
      { symbol: 'BRK.B', name: 'Berkshire B', weight: 13.4, sector: 'Financials' },
      { symbol: 'JPM', name: 'JPMorgan', weight: 11.2, sector: 'Financials' },
      { symbol: 'V', name: 'Visa', weight: 8.4, sector: 'Financials' },
      { symbol: 'MA', name: 'Mastercard', weight: 6.8, sector: 'Financials' },
      { symbol: 'BAC', name: 'Bank of America', weight: 5.2, sector: 'Financials' },
      { symbol: 'WFC', name: 'Wells Fargo', weight: 4.1, sector: 'Financials' },
      { symbol: 'GS', name: 'Goldman Sachs', weight: 3.8, sector: 'Financials' },
      { symbol: 'MS', name: 'Morgan Stanley', weight: 3.2, sector: 'Financials' },
      { symbol: 'SPGI', name: 'S&P Global', weight: 3.0, sector: 'Financials' },
      { symbol: 'BLK', name: 'BlackRock', weight: 2.8, sector: 'Financials' },
    ],
    sectors: [{ name: 'Financials', weight: 99.1 }, { name: 'Other', weight: 0.9 }],
    stressTests: { gfc2008: -79, covid2020: -38, rateShock2022: -14 },
    flags: { currencyHedged: false, swapBased: false, concentrationRisk: true, esgScreened: false },
    distFreq: 'Quarterly',
  },
  {
    symbol: 'XLV', name: 'Health Care Select Sector SPDR', issuer: 'State Street',
    category: 'US Sector', benchmark: 'Health Care Select Sector Index',
    aum: '40B', er: 0.10, holdings: 63, domicile: 'US',
    replication: 'Physical', esgScore: null,
    topHoldings: [
      { symbol: 'LLY', name: 'Eli Lilly', weight: 11.8, sector: 'Healthcare' },
      { symbol: 'UNH', name: 'UnitedHealth', weight: 9.4, sector: 'Healthcare' },
      { symbol: 'JNJ', name: 'Johnson & Johnson', weight: 6.8, sector: 'Healthcare' },
      { symbol: 'ABT', name: 'Abbott', weight: 4.9, sector: 'Healthcare' },
      { symbol: 'MRK', name: 'Merck', weight: 4.7, sector: 'Healthcare' },
      { symbol: 'TMO', name: 'Thermo Fisher', weight: 4.1, sector: 'Healthcare' },
      { symbol: 'ABBV', name: 'AbbVie', weight: 3.8, sector: 'Healthcare' },
      { symbol: 'AMGN', name: 'Amgen', weight: 3.2, sector: 'Healthcare' },
      { symbol: 'ISRG', name: 'Intuitive Surgical', weight: 2.9, sector: 'Healthcare' },
      { symbol: 'PFE', name: 'Pfizer', weight: 2.7, sector: 'Healthcare' },
    ],
    sectors: [{ name: 'Healthcare', weight: 99.8 }, { name: 'Other', weight: 0.2 }],
    stressTests: { gfc2008: -32, covid2020: -24, rateShock2022: -4 },
    flags: { currencyHedged: false, swapBased: false, concentrationRisk: false, esgScreened: false },
    distFreq: 'Quarterly',
  },
  {
    symbol: 'XLE', name: 'Energy Select Sector SPDR', issuer: 'State Street',
    category: 'US Sector', benchmark: 'Energy Select Sector Index',
    aum: '35B', er: 0.10, holdings: 23, domicile: 'US',
    replication: 'Physical', esgScore: null,
    topHoldings: [
      { symbol: 'XOM', name: 'ExxonMobil', weight: 22.4, sector: 'Energy' },
      { symbol: 'CVX', name: 'Chevron', weight: 18.2, sector: 'Energy' },
      { symbol: 'COP', name: 'ConocoPhillips', weight: 7.8, sector: 'Energy' },
      { symbol: 'EOG', name: 'EOG Resources', weight: 5.4, sector: 'Energy' },
      { symbol: 'SLB', name: 'SLB', weight: 4.9, sector: 'Energy' },
      { symbol: 'MPC', name: 'Marathon Petroleum', weight: 4.2, sector: 'Energy' },
      { symbol: 'PSX', name: 'Phillips 66', weight: 4.1, sector: 'Energy' },
      { symbol: 'PXD', name: 'Pioneer Natural', weight: 3.8, sector: 'Energy' },
      { symbol: 'VLO', name: 'Valero Energy', weight: 3.2, sector: 'Energy' },
      { symbol: 'WMB', name: 'Williams Companies', weight: 2.9, sector: 'Energy' },
    ],
    sectors: [{ name: 'Energy', weight: 99.7 }, { name: 'Other', weight: 0.3 }],
    stressTests: { gfc2008: -55, covid2020: -50, rateShock2022: 57 },
    flags: { currencyHedged: false, swapBased: false, concentrationRisk: true, esgScreened: false },
    distFreq: 'Quarterly',
  },
  {
    symbol: 'XLI', name: 'Industrial Select Sector SPDR', issuer: 'State Street',
    category: 'US Sector', benchmark: 'Industrial Select Sector Index',
    aum: '22B', er: 0.10, holdings: 78, domicile: 'US',
    replication: 'Physical', esgScore: null,
    topHoldings: [
      { symbol: 'GE', name: 'GE Aerospace', weight: 5.8, sector: 'Industrials' },
      { symbol: 'RTX', name: 'RTX Corp', weight: 5.2, sector: 'Industrials' },
      { symbol: 'CAT', name: 'Caterpillar', weight: 5.0, sector: 'Industrials' },
      { symbol: 'HON', name: 'Honeywell', weight: 4.8, sector: 'Industrials' },
      { symbol: 'UNP', name: 'Union Pacific', weight: 4.4, sector: 'Industrials' },
      { symbol: 'UPS', name: 'UPS', weight: 3.8, sector: 'Industrials' },
      { symbol: 'DE', name: 'Deere', weight: 3.6, sector: 'Industrials' },
      { symbol: 'LMT', name: 'Lockheed Martin', weight: 3.4, sector: 'Industrials' },
      { symbol: 'ETN', name: 'Eaton', weight: 3.2, sector: 'Industrials' },
      { symbol: 'ADP', name: 'ADP', weight: 2.9, sector: 'Industrials' },
    ],
    sectors: [{ name: 'Industrials', weight: 99.2 }, { name: 'Other', weight: 0.8 }],
    stressTests: { gfc2008: -53, covid2020: -36, rateShock2022: -18 },
    flags: { currencyHedged: false, swapBased: false, concentrationRisk: false, esgScreened: false },
    distFreq: 'Quarterly',
  },
  // ── International ─────────────────────────────────────────────────────────
  {
    symbol: 'VEA', name: 'Vanguard FTSE Developed Markets ETF', issuer: 'Vanguard',
    category: 'International', benchmark: 'FTSE Developed All Cap ex US',
    aum: '118B', er: 0.05, holdings: 3900, domicile: 'US',
    replication: 'Sampling', esgScore: null,
    topHoldings: [
      { symbol: 'NESN', name: 'Nestle', weight: 1.42, sector: 'Consumer Staples' },
      { symbol: 'ASML', name: 'ASML', weight: 1.38, sector: 'Technology' },
      { symbol: 'NOVN', name: 'Novartis', weight: 1.21, sector: 'Healthcare' },
      { symbol: 'ROG', name: 'Roche', weight: 1.18, sector: 'Healthcare' },
      { symbol: 'SHEL', name: 'Shell', weight: 1.12, sector: 'Energy' },
      { symbol: '7203', name: 'Toyota', weight: 1.08, sector: 'Consumer Disc.' },
      { symbol: 'AZN', name: 'AstraZeneca', weight: 0.98, sector: 'Healthcare' },
      { symbol: 'HSBA', name: 'HSBC', weight: 0.94, sector: 'Financials' },
      { symbol: 'SAP', name: 'SAP', weight: 0.91, sector: 'Technology' },
      { symbol: 'LVMH', name: 'LVMH', weight: 0.88, sector: 'Consumer Disc.' },
    ],
    sectors: [
      { name: 'Financials', weight: 20.4 }, { name: 'Industrials', weight: 16.2 },
      { name: 'Healthcare', weight: 12.8 }, { name: 'Consumer Disc.', weight: 11.4 },
      { name: 'Consumer Staples', weight: 10.8 }, { name: 'Technology', weight: 9.4 },
      { name: 'Materials', weight: 6.8 }, { name: 'Energy', weight: 5.2 },
      { name: 'Utilities', weight: 3.8 }, { name: 'Comm. Services', weight: 3.2 },
    ],
    stressTests: { gfc2008: -55, covid2020: -34, rateShock2022: -24 },
    flags: { currencyHedged: false, swapBased: false, concentrationRisk: false, esgScreened: false },
    distFreq: 'Semi-annual',
  },
  {
    symbol: 'EEM', name: 'iShares MSCI Emerging Markets ETF', issuer: 'iShares (BlackRock)',
    category: 'International', benchmark: 'MSCI Emerging Markets',
    aum: '18B', er: 0.68, holdings: 1200, domicile: 'US',
    replication: 'Sampling', esgScore: null,
    topHoldings: [
      { symbol: 'TSM', name: 'TSMC', weight: 8.42, sector: 'Technology' },
      { symbol: '700', name: 'Tencent', weight: 4.18, sector: 'Comm. Services' },
      { symbol: '005930', name: 'Samsung', weight: 3.84, sector: 'Technology' },
      { symbol: 'BABA', name: 'Alibaba', weight: 2.94, sector: 'Consumer Disc.' },
      { symbol: 'RELIANCE', name: 'Reliance Industries', weight: 1.82, sector: 'Energy' },
      { symbol: 'MEITUAN', name: 'Meituan', weight: 1.54, sector: 'Consumer Disc.' },
      { symbol: 'HDFC', name: 'HDFC Bank', weight: 1.42, sector: 'Financials' },
      { symbol: 'JD', name: 'JD.com', weight: 1.28, sector: 'Consumer Disc.' },
      { symbol: 'INFOSYS', name: 'Infosys', weight: 1.14, sector: 'Technology' },
      { symbol: 'ICBC', name: 'ICBC', weight: 1.08, sector: 'Financials' },
    ],
    sectors: [
      { name: 'Technology', weight: 22.4 }, { name: 'Financials', weight: 20.8 },
      { name: 'Consumer Disc.', weight: 13.4 }, { name: 'Comm. Services', weight: 10.2 },
      { name: 'Materials', weight: 8.4 }, { name: 'Energy', weight: 6.8 },
      { name: 'Industrials', weight: 6.2 }, { name: 'Consumer Staples', weight: 5.4 },
      { name: 'Healthcare', weight: 3.8 }, { name: 'Utilities', weight: 2.6 },
    ],
    stressTests: { gfc2008: -62, covid2020: -32, rateShock2022: -22 },
    flags: { currencyHedged: false, swapBased: false, concentrationRisk: false, esgScreened: false },
    distFreq: 'Semi-annual',
  },
  // ── Fixed Income ──────────────────────────────────────────────────────────
  {
    symbol: 'AGG', name: 'iShares Core US Aggregate Bond ETF', issuer: 'iShares (BlackRock)',
    category: 'Fixed Income', benchmark: 'Bloomberg US Aggregate Bond',
    aum: '110B', er: 0.03, holdings: 11000, domicile: 'US',
    replication: 'Sampling', esgScore: null, duration: 6.2, ytm: 4.8,
    topHoldings: [
      { symbol: 'UST', name: 'US Treasuries', weight: 42.8, sector: 'Fixed Income' },
      { symbol: 'MBS', name: 'Mortgage-Backed', weight: 26.4, sector: 'Fixed Income' },
      { symbol: 'CORP', name: 'Investment Grade Corp', weight: 24.2, sector: 'Fixed Income' },
      { symbol: 'AGENCY', name: 'Agency Bonds', weight: 4.8, sector: 'Fixed Income' },
      { symbol: 'OTHER', name: 'Other', weight: 1.8, sector: 'Fixed Income' },
    ],
    sectors: [
      { name: 'Fixed Income', weight: 100 },
    ],
    stressTests: { gfc2008: 5, covid2020: 2, rateShock2022: -16 },
    flags: { currencyHedged: false, swapBased: false, concentrationRisk: false, esgScreened: false },
    distFreq: 'Monthly',
  },
  {
    symbol: 'TLT', name: 'iShares 20+ Year Treasury Bond ETF', issuer: 'iShares (BlackRock)',
    category: 'Fixed Income', benchmark: 'ICE US Treasury 20+ Year',
    aum: '58B', er: 0.15, holdings: 44, domicile: 'US',
    replication: 'Physical', esgScore: null, duration: 16.8, ytm: 4.6,
    topHoldings: [
      { symbol: 'UST30', name: '30Y US Treasury', weight: 51.2, sector: 'Fixed Income' },
      { symbol: 'UST20', name: '20Y US Treasury', weight: 48.8, sector: 'Fixed Income' },
    ],
    sectors: [{ name: 'Fixed Income', weight: 100 }],
    stressTests: { gfc2008: 26, covid2020: 21, rateShock2022: -36 },
    flags: { currencyHedged: false, swapBased: false, concentrationRisk: false, esgScreened: false },
    distFreq: 'Monthly',
  },
  {
    symbol: 'HYG', name: 'iShares iBoxx High Yield Corporate Bond ETF', issuer: 'iShares (BlackRock)',
    category: 'Fixed Income', benchmark: 'Markit iBoxx USD Liquid High Yield',
    aum: '14B', er: 0.48, holdings: 1200, domicile: 'US',
    replication: 'Sampling', esgScore: null, duration: 3.6, ytm: 7.4,
    topHoldings: [
      { symbol: 'HY_CORP', name: 'High Yield Corporates', weight: 96.4, sector: 'Fixed Income' },
      { symbol: 'CASH', name: 'Cash & Equiv', weight: 3.6, sector: 'Fixed Income' },
    ],
    sectors: [{ name: 'Fixed Income', weight: 100 }],
    stressTests: { gfc2008: -26, covid2020: -21, rateShock2022: -15 },
    flags: { currencyHedged: false, swapBased: false, concentrationRisk: false, esgScreened: false },
    distFreq: 'Monthly',
  },
  // ── Alternatives ──────────────────────────────────────────────────────────
  {
    symbol: 'GLD', name: 'SPDR Gold Shares', issuer: 'State Street',
    category: 'Alternatives', benchmark: 'Gold Spot Price',
    aum: '65B', er: 0.40, holdings: 1, domicile: 'US',
    replication: 'Physical', esgScore: null,
    topHoldings: [
      { symbol: 'GOLD', name: 'Physical Gold', weight: 100, sector: 'Other' },
    ],
    sectors: [{ name: 'Other', weight: 100 }],
    stressTests: { gfc2008: 5, covid2020: 4, rateShock2022: -2 },
    flags: { currencyHedged: false, swapBased: false, concentrationRisk: false, esgScreened: false },
    distFreq: 'None',
  },
  {
    symbol: 'VNQ', name: 'Vanguard Real Estate ETF', issuer: 'Vanguard',
    category: 'Alternatives', benchmark: 'MSCI US Investable Market Real Estate 25/50',
    aum: '35B', er: 0.12, holdings: 166, domicile: 'US',
    replication: 'Physical', esgScore: null,
    topHoldings: [
      { symbol: 'PLD', name: 'Prologis', weight: 8.94, sector: 'Real Estate' },
      { symbol: 'AMT', name: 'American Tower', weight: 7.12, sector: 'Real Estate' },
      { symbol: 'EQIX', name: 'Equinix', weight: 6.48, sector: 'Real Estate' },
      { symbol: 'WELL', name: 'Welltower', weight: 5.24, sector: 'Real Estate' },
      { symbol: 'PSA', name: 'Public Storage', weight: 4.87, sector: 'Real Estate' },
      { symbol: 'DLR', name: 'Digital Realty', weight: 4.32, sector: 'Real Estate' },
      { symbol: 'O', name: 'Realty Income', weight: 3.98, sector: 'Real Estate' },
      { symbol: 'SPG', name: 'Simon Property', weight: 3.74, sector: 'Real Estate' },
      { symbol: 'CCI', name: 'Crown Castle', weight: 3.41, sector: 'Real Estate' },
      { symbol: 'AVB', name: 'AvalonBay', weight: 3.18, sector: 'Real Estate' },
    ],
    sectors: [{ name: 'Real Estate', weight: 99.2 }, { name: 'Other', weight: 0.8 }],
    stressTests: { gfc2008: -68, covid2020: -40, rateShock2022: -29 },
    flags: { currencyHedged: false, swapBased: false, concentrationRisk: false, esgScreened: false },
    distFreq: 'Quarterly',
  },
]

export const ETF_BY_SYMBOL = Object.fromEntries(ETF_UNIVERSE.map(e => [e.symbol, e]))

export const CATEGORIES = ['All', 'US Equity Broad', 'US Equity Factor', 'US Sector', 'International', 'Fixed Income', 'Alternatives']

export const DEFAULT_SELECTION = ['SPY', 'QQQ', 'VTI']
